[2023-04-26T17:20:25.513+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.python_task1 manual__2023-04-26T17:20:22.956572+00:00 [queued]>
[2023-04-26T17:20:25.569+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.python_task1 manual__2023-04-26T17:20:22.956572+00:00 [queued]>
[2023-04-26T17:20:25.572+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T17:20:25.573+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T17:20:25.574+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T17:20:25.673+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): python_task1> on 2023-04-26 17:20:22.956572+00:00
[2023-04-26T17:20:25.692+0000] {standard_task_runner.py:55} INFO - Started process 5555 to run task
[2023-04-26T17:20:25.700+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'python_task1', 'manual__2023-04-26T17:20:22.956572+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_final.py', '--cfg-path', '/tmp/tmpy4dkk_al']
[2023-04-26T17:20:25.706+0000] {standard_task_runner.py:83} INFO - Job 536: Subtask python_task1
[2023-04-26T17:20:25.872+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.python_task1 manual__2023-04-26T17:20:22.956572+00:00 [running]> on host d48b88797b3b
[2023-04-26T17:20:26.780+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=python_task1
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T17:20:22.956572+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T17:20:22.956572+00:00
[2023-04-26T17:20:26.783+0000] {weather_dag_final.py:24} INFO - Starting db creation
[2023-04-26T17:20:26.787+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-26T17:20:26.870+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag_api, task_id=python_task1, execution_date=20230426T172022, start_date=20230426T172025, end_date=20230426T172026
[2023-04-26T17:20:26.973+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-26T17:20:27.070+0000] {dagrun.py:697} ERROR - Failed to get task for ti <TaskInstance: weather_dag_api.cities.view_data_Kyiv manual__2023-04-26T17:20:22.956572+00:00 [None]>. Marking it as removed.
[2023-04-26T17:20:27.082+0000] {dagrun.py:697} ERROR - Failed to get task for ti <TaskInstance: weather_dag_api.cities.view_data_Kharkiv manual__2023-04-26T17:20:22.956572+00:00 [None]>. Marking it as removed.
[2023-04-26T17:20:27.086+0000] {dagrun.py:697} ERROR - Failed to get task for ti <TaskInstance: weather_dag_api.cities.view_data_Odesa manual__2023-04-26T17:20:22.956572+00:00 [None]>. Marking it as removed.
[2023-04-26T17:20:27.091+0000] {dagrun.py:697} ERROR - Failed to get task for ti <TaskInstance: weather_dag_api.cities.view_data_Zhmerynka manual__2023-04-26T17:20:22.956572+00:00 [None]>. Marking it as removed.
[2023-04-26T17:20:27.095+0000] {dagrun.py:697} ERROR - Failed to get task for ti <TaskInstance: weather_dag_api.cities.view_data_Lviv manual__2023-04-26T17:20:22.956572+00:00 [None]>. Marking it as removed.
[2023-04-26T17:20:27.132+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
