[2023-04-26T13:38:29.479+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag_api.insert_data manual__2023-04-26T13:38:11.220127+00:00 [queued]>
[2023-04-26T13:38:29.578+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag_api.insert_data manual__2023-04-26T13:38:11.220127+00:00 [queued]>
[2023-04-26T13:38:29.580+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T13:38:29.582+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-26T13:38:29.584+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T13:38:29.754+0000] {taskinstance.py:1309} INFO - Executing <Task(PostgresOperator): insert_data> on 2023-04-26 13:38:11.220127+00:00
[2023-04-26T13:38:29.830+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weather_dag_api', 'insert_data', 'manual__2023-04-26T13:38:11.220127+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag_api.py', '--cfg-path', '/tmp/tmpulg1jjzc']
[2023-04-26T13:38:29.837+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask insert_data
[2023-04-26T13:38:29.805+0000] {standard_task_runner.py:55} INFO - Started process 473 to run task
[2023-04-26T13:38:30.291+0000] {task_command.py:389} INFO - Running <TaskInstance: weather_dag_api.insert_data manual__2023-04-26T13:38:11.220127+00:00 [running]> on host d48b88797b3b
[2023-04-26T13:38:31.231+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_dag_api
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T13:38:11.220127+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T13:38:11.220127+00:00
[2023-04-26T13:38:31.239+0000] {sql.py:254} INFO - Executing: INSERT INTO measurements (timestamp, temp, precipitation, wind_speed)
		VALUES ('2023-04-25T10:20:00Z',
		15.1,
		0.0,
		2.0);
[2023-04-26T13:38:31.271+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T13:38:32.380+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-04-26T13:38:32.392+0000] {sql.py:375} INFO - Running statement: INSERT INTO measurements (timestamp, temp, precipitation, wind_speed)
		VALUES ('2023-04-25T10:20:00Z',
		15.1,
		0.0,
		2.0);, parameters: None
[2023-04-26T13:38:32.398+0000] {sql.py:384} INFO - Rows affected: 1
[2023-04-26T13:38:32.439+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=weather_dag_api, task_id=insert_data, execution_date=20230426T133811, start_date=20230426T133829, end_date=20230426T133832
[2023-04-26T13:38:32.510+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-26T13:38:32.631+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
